#!/usr/bin/env ruby

require 'open3'

if ARGV.count != 1
    puts "Usage: #{$0} <migrator-command>"
    exit 0
end

$action = ARGV[0]

class ACTION
    MIGRATE = "migrate"
    GENERATE = "generate"
    COMPARE = "compare"
end

def command(action:)
    base = "swift run migrator"
    target = "/Users/eld/Desktop/QONECTIQ"
    packageName = "QONECTIQ"
    oldAPI = "api_v1.0.0.json"
    newAPI = "api_v2.0.0.json"

    case action
    when ACTION::MIGRATE
        return "#{base} migrate -t=#{target} -d=#{target}/#{oldAPI} -m=#{target}/migration_guide.json -p=#{packageName}"
    when ACTION::GENERATE
        return "#{base} generate -d=#{target}/#{oldAPI} -p=#{packageName} -t=#{target}"
    when ACTION::COMPARE
        return "#{base} compare -o=#{target}/#{oldAPI} -n=#{target}/#{newAPI} -m=#{target}"
    else
        puts "Usage: #{$0} | Use one of the following commands: <generate> or <compare>. After generating the migration guide with the <compare> command, the library can be migrated via <migrate>"
        exit 0
    end
end



def migrator()
    cmd = command(action: $action)
    Open3.popen3(cmd) do |stdin, stdout, stderr, wait_thr|
        puts stdout.read
        puts stderr.read
    end
end

migrator()
