//
// This source file is part of the Apodini open source project
//
// SPDX-FileCopyrightText: 2019-2021 Paul Schmiedmayer and the Apodini project authors (see CONTRIBUTORS.md) <paul.schmiedmayer@tum.de>
//
// SPDX-License-Identifier: MIT
//

import Foundation

/// An object that renders the header comment of a `Swift` file generated by `ApodiniMigrator`
public struct FileHeaderComment: SourceCodeRenderable {
    static var testsDate: Date?

    public init() {}

    /// Returns the content of the file header comment
    public var renderableContent: String {
        let date = Self.testsDate ?? .init()

        """
        //
        //  Created by ApodiniMigrator on \(date.string(.date))
        //  Copyright \u{00A9} \(date.string(.year)) TUM LS1. All rights reserved.
        //

        """
    }
}
